version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 10
    versioning-strategy: widen
    ignore:
      - dependency-name: '@types/express'
        versions:
          - '> 4.17.1'
