version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/express"
    versions:
    - "> 4.17.1"
  - dependency-name: ts-loader
    versions:
    - 9.0.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.21.0
  - dependency-name: "@nestjs/platform-express"
    versions:
    - 7.6.11
    - 7.6.12
    - 7.6.14
    - 7.6.15
    - 7.6.7
    - 7.6.9
  - dependency-name: "@nestjs/typeorm"
    versions:
    - 7.1.5
  - dependency-name: "@nestjs/testing"
    versions:
    - 7.6.11
    - 7.6.12
    - 7.6.14
    - 7.6.7
    - 7.6.9
  - dependency-name: "@nestjs/common"
    versions:
    - 7.6.14
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.34
  - dependency-name: "@nestjs/core"
    versions:
    - 7.6.11
    - 7.6.12
    - 7.6.13
    - 7.6.14
    - 7.6.7
    - 7.6.9
  - dependency-name: typeorm
    versions:
    - 0.2.30
  - dependency-name: rxjs
    versions:
    - 6.6.3
