name: E2E test

on: [push]

jobs:
  e2e-test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: bahmutov/npm-install@v1
    - name: Run E2E tests
      run: |
        npm run test:e2e
      env:
        CI: 'true'
        PORT: 3000
