name: Tests

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Unit test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: bahmutov/npm-install@v1
      - name: Run unit test
        run: |
          npm test
        env:
          CI: 'true'
          PORT: 3000

  e2e-test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: E2E test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: bahmutov/npm-install@v1
      - name: Run E2E tests
        run: |
          npm run test:e2e
        env:
          CI: 'true'
          PORT: 3000
